// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 包括人口学特征，一些上下文特征等，后面会一直透传这些特征。
type RecReq struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Gender               string   `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	AppVersion           string   `protobuf:"bytes,5,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	Network              string   `protobuf:"bytes,6,opt,name=network,proto3" json:"network,omitempty"`
	PageNum              int32    `protobuf:"varint,7,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize             int32    `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecReq) Reset()         { *m = RecReq{} }
func (m *RecReq) String() string { return proto.CompactTextString(m) }
func (*RecReq) ProtoMessage()    {}
func (*RecReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *RecReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecReq.Unmarshal(m, b)
}
func (m *RecReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecReq.Marshal(b, m, deterministic)
}
func (m *RecReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecReq.Merge(m, src)
}
func (m *RecReq) XXX_Size() int {
	return xxx_messageInfo_RecReq.Size(m)
}
func (m *RecReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RecReq.DiscardUnknown(m)
}

var xxx_messageInfo_RecReq proto.InternalMessageInfo

func (m *RecReq) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *RecReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RecReq) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *RecReq) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *RecReq) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *RecReq) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *RecReq) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *RecReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type RecRespItem struct {
	ItemId               string   `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Params               string   `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecRespItem) Reset()         { *m = RecRespItem{} }
func (m *RecRespItem) String() string { return proto.CompactTextString(m) }
func (*RecRespItem) ProtoMessage()    {}
func (*RecRespItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *RecRespItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecRespItem.Unmarshal(m, b)
}
func (m *RecRespItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecRespItem.Marshal(b, m, deterministic)
}
func (m *RecRespItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecRespItem.Merge(m, src)
}
func (m *RecRespItem) XXX_Size() int {
	return xxx_messageInfo_RecRespItem.Size(m)
}
func (m *RecRespItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RecRespItem.DiscardUnknown(m)
}

var xxx_messageInfo_RecRespItem proto.InternalMessageInfo

func (m *RecRespItem) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *RecRespItem) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

type RecResp struct {
	Items                []*RecRespItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RecResp) Reset()         { *m = RecResp{} }
func (m *RecResp) String() string { return proto.CompactTextString(m) }
func (*RecResp) ProtoMessage()    {}
func (*RecResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *RecResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecResp.Unmarshal(m, b)
}
func (m *RecResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecResp.Marshal(b, m, deterministic)
}
func (m *RecResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecResp.Merge(m, src)
}
func (m *RecResp) XXX_Size() int {
	return xxx_messageInfo_RecResp.Size(m)
}
func (m *RecResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RecResp.DiscardUnknown(m)
}

var xxx_messageInfo_RecResp proto.InternalMessageInfo

func (m *RecResp) GetItems() []*RecRespItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*RecReq)(nil), "api.RecReq")
	proto.RegisterType((*RecRespItem)(nil), "api.RecRespItem")
	proto.RegisterType((*RecResp)(nil), "api.RecResp")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x09, 0xa1, 0x76, 0x7b, 0x61, 0xa8, 0x3c, 0x80, 0xa1, 0x42, 0x54, 0x19, 0x50, 0x58,
	0x1a, 0x51, 0x76, 0x06, 0xb6, 0x2c, 0x0c, 0x46, 0x62, 0x60, 0x89, 0xdc, 0xe4, 0x14, 0x59, 0x90,
	0xc4, 0xb5, 0x93, 0x22, 0xf5, 0x9f, 0xf2, 0x6f, 0x90, 0xed, 0xa2, 0x76, 0xca, 0x7d, 0xf7, 0xde,
	0x5d, 0xfc, 0x6c, 0x98, 0x49, 0xad, 0x56, 0xda, 0xf4, 0x43, 0xcf, 0x62, 0xa9, 0x55, 0xfa, 0x1b,
	0x01, 0x11, 0x58, 0x09, 0xdc, 0xb2, 0x1b, 0x98, 0x0e, 0x46, 0x56, 0x58, 0xaa, 0x9a, 0x47, 0xcb,
	0x28, 0x9b, 0x09, 0xea, 0xb9, 0xa8, 0xd9, 0x35, 0xd0, 0xd1, 0xa2, 0x71, 0xca, 0xb9, 0x57, 0x88,
	0xc3, 0xa2, 0x66, 0x57, 0x40, 0x1a, 0xec, 0x6a, 0x34, 0x3c, 0x0e, 0xfd, 0x40, 0x6c, 0x0e, 0xb1,
	0x6c, 0x90, 0x5f, 0x2c, 0xa3, 0x6c, 0x22, 0x5c, 0xc9, 0xee, 0x21, 0x91, 0x5a, 0x97, 0x3b, 0x34,
	0x56, 0xf5, 0x1d, 0x9f, 0x78, 0x3b, 0x48, 0xad, 0x3f, 0x42, 0x87, 0x71, 0xa0, 0x1d, 0x0e, 0x3f,
	0xbd, 0xf9, 0xe2, 0x24, 0xfc, 0xfd, 0x80, 0xee, 0x60, 0x5a, 0x36, 0x58, 0x76, 0x63, 0xcb, 0xa9,
	0xdf, 0x48, 0x1d, 0xbf, 0x8d, 0x2d, 0x5b, 0xc0, 0xcc, 0x4b, 0x56, 0xed, 0x91, 0x4f, 0xbd, 0xe6,
	0xbd, 0xef, 0x6a, 0x8f, 0xe9, 0x0b, 0x24, 0x3e, 0x9a, 0xd5, 0xc5, 0x80, 0xad, 0x0b, 0xa1, 0x06,
	0x6c, 0x8f, 0xf1, 0x88, 0xc3, 0x10, 0x42, 0x4b, 0x23, 0x5b, 0xfb, 0x1f, 0x2e, 0x50, 0xfa, 0x04,
	0xf4, 0x30, 0xcf, 0x1e, 0x60, 0xe2, 0xcc, 0x96, 0x47, 0xcb, 0x38, 0x4b, 0xd6, 0xf3, 0x95, 0xbb,
	0xc6, 0x93, 0xe5, 0x22, 0xc8, 0xeb, 0x47, 0x88, 0x05, 0x56, 0x2c, 0x0d, 0x9f, 0xe4, 0x68, 0xdb,
	0xde, 0x5e, 0x9e, 0xce, 0xa4, 0x67, 0xaf, 0x77, 0x9f, 0x8b, 0xa6, 0x2f, 0x2d, 0x9a, 0x1d, 0x9a,
	0xdc, 0x9a, 0x2a, 0xff, 0x56, 0x9b, 0xdc, 0xbf, 0x4c, 0x2e, 0xb5, 0xda, 0x10, 0x5f, 0x3e, 0xff,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x25, 0x85, 0x88, 0xb1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecClient is the client API for Rec service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecClient interface {
	Rec(ctx context.Context, in *RecReq, opts ...grpc.CallOption) (*RecResp, error)
}

type recClient struct {
	cc *grpc.ClientConn
}

func NewRecClient(cc *grpc.ClientConn) RecClient {
	return &recClient{cc}
}

func (c *recClient) Rec(ctx context.Context, in *RecReq, opts ...grpc.CallOption) (*RecResp, error) {
	out := new(RecResp)
	err := c.cc.Invoke(ctx, "/api.Rec/Rec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecServer is the server API for Rec service.
type RecServer interface {
	Rec(context.Context, *RecReq) (*RecResp, error)
}

// UnimplementedRecServer can be embedded to have forward compatible implementations.
type UnimplementedRecServer struct {
}

func (*UnimplementedRecServer) Rec(ctx context.Context, req *RecReq) (*RecResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rec not implemented")
}

func RegisterRecServer(s *grpc.Server, srv RecServer) {
	s.RegisterService(&_Rec_serviceDesc, srv)
}

func _Rec_Rec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecServer).Rec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Rec/Rec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecServer).Rec(ctx, req.(*RecReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rec_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Rec",
	HandlerType: (*RecServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Rec",
			Handler:    _Rec_Rec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
